sensors:
    logical_camera_1:
      type: logical_camera
      pose:
        xyz: [1.2, 3.5, 1.5]
        rpy: [0, 1.5707, 0]
    depth_camera_1:
      type: depth_camera
      pose:
        xyz: [0.875, 0.75, 1.3]
        rpy: [0, 1, 0]
