# Competition configuration options
options:
  insert_models_over_bins: true     # Whether or not to insert the models that are specified in models_over_bins
  spawn_extra_models: true          # Whether or not to spawn the models that are specified in models_to_spawn
  gazebo_state_logging: true        # Whether or not to generate a gazebo state log
  belt_population_cycles: 5         # How many cycles to spawn parts on the conveyor
  model_type_aliases:               # Aliases for model types which can be used in the configuration file
    order_part1: piston_rod_part    # Wherever 'order_part1' is used in the configuration file, use 'piston_rod_part'
    order_part2: gear_part
    order_part3: pulley_part
  visualize_drop_regions: false     # Whether or not to visualize drop regions (world frame only)

time_limit: 600                      # Maximum time allowed for the trial once started, in seconds
random_seed: 1                       # Seed for the pseudo random number generator (used to randomize model names)
