# ROS Dockerfile

# Use official image for ROS Melodic Morenia
FROM ros:melodic

# Install turtlesim dependencies
RUN sudo apt-get update && apt-get install -y \
        ros-melodic-ros-tutorials

CMD ["/bin/bash"]
