# ROS Dockerfile

# Use official image for ROS Melodic Morenia
FROM ros:melodic

# Install dependencies for development
RUN sudo apt-get update && apt-get install -y \
        build-essential

CMD ["/bin/bash"]
